Defered in pools
DrFaust92/terraform-provider-airflow pull request #36
Opened 2023-09-11 10:09 UTC by tim-habitat

attempt at adding https://github.com/DrFaust92/terraform-provider-airflow/issues/35

2023-09-15 08:57 UTC, tim-habitat commented
hey @DrFaust92 what do you think of adding this toggle to the `pools` ? :)

2023-09-15 10:27 UTC, DrFaust92 requested changes
See comments, plus missing documentation.

2023-09-15 10:27 UTC, DrFaust92 commented on internal/provider/resource_pool.go
> +	d.Set("include_deferred", includeDeferred)
Why? Should be set on read

2023-09-15 10:27 UTC, DrFaust92 commented on internal/provider/resource_pool.go
> +	includeDeferred := d.Get("include_deferred").(bool)
Extraneous, let's align with other set examples on that are above this do d.Get(...) inline in the set call

2023-09-15 10:27 UTC, DrFaust92 commented on internal/provider/resource_pool.go
> +	d.Set("include_deferred", includeDeferred)
Same as above in create func

2023-09-15 10:27 UTC, DrFaust92 commented on internal/provider/resource_pool_test.go
> +				Config: testAccAirflowPoolConfigBasic(rName, 2, true),
Let's not change the existing test and add a new one

2023-09-15 10:32 UTC, DrFaust92 commented
Ok, I see the problem. This won't work (yet) as the provider is using an older version of the go sdk (2.5.0) and needs 2.7.0 to support this parameter. So we cannot merge this yet, and as far as I recall the go sdk hasn't been built yet for 2.7.0 and requires action upstream.

address the comments for now and I'll take a look at updating the sdk version. 

I'm currently on vacation so this won't happen until at least 2 weeks from now. I'll try to get to this asap

2023-11-27 09:52 UTC, closed without merging

2023-12-12 06:59 UTC, kmehkeri commented
Any chance to have this? I would be happy to contribute if needed, just having the baseline would be helpful, is it possible to restore @tim-habitat?

2023-12-12 07:09 UTC, tim-habitat commented
hey @kmehkeri sure, here i reinstated it and rebased off the curreent latest master of this repo.

2023-12-30 22:21 UTC, kmehkeri commented
Uh... I went into this and only now realized what exactly DrFaust's earlier comment was about (dependency on PRs in [Go Airflow client](https://github.com/apache/airflow-client-go/pull/43) and [Airflow](https://github.com/apache/airflow/pull/34805) itself). So indeed this needs to wait :/

2024-07-31 19:17 UTC, brokenjacobs commented
Any updates @DrFaust92 ? I tried implementing this and ran into the same issue with the upstream airflow-go sdk... Since it's just generated from the openAPI spec seems we could just make another project for it if they won't maintain it...

2025-10-31 19:40 UTC, DrFaust92 commented
available in 0.18.1